public class DeterminePaymentTabController{
	/*
    public CatTabDefault__c Determine_PaymentTab{get; set;}   
    public list<CatTabDefault__c> catset {get; set;}   
    public String links;
         //Constructor with no arguments 
    public DeterminePaymentTabController() {
        
        catset = CatTabDefault__c.getAll().values();
        Determine_PaymentTab= CatTabDefault__c.getInstance('Determine Payment');
        
        //SOQL to retrieve data from
        
        //links= [SELECT Links__c FROM Category_Tab_Link__kav WHERE PublishStatus = 'online' AND Language = 'en_US' AND UrlName =:Determine_PaymentTab.Category_Links__c].Links__c;
            
         }         
      
         
     public String getDetcatlinks() {
        return links;      
    }
 	*/
}