public class ProcessingTabController{
   	/*
    public CatTabDefault__c ProcessingTab {get; set;}    
    public list<CatTabDefault__c> catset {get; set;}
           
    public String links;
    
     //Constructor with no arguments 
    public ProcessingTabController() {
        
        catset = CatTabDefault__c.getAll().values();       
        ProcessingTab = CatTabDefault__c.getInstance('Processing');
        
        //SOQL to search articles filtered by Data-Categories
        
        //SOQL to retrieve data from
        //links= [SELECT Links__c FROM Category_Tab_Link__kav WHERE PublishStatus = 'online' AND Language = 'en_US' AND UrlName =: ProcessingTab.Category_Links__c].Links__c;
              
         }         
      
 
     public String getProcessingcatlinks() {
        return links;      
    }
	*/
}