public class AdjustmentsTabController{       
    /*
    public CatTabDefault__c AdjustmentsTab {get; set;}  
    public list<CatTabDefault__c> catset {get; set;}
    public String links;
    
    public AdjustmentsTabController() {
        catset = CatTabDefault__c.getAll().values();
        AdjustmentsTab = CatTabDefault__c.getInstance('Adjustments');        
    //SOQL to search articles filtered by Data-Categories   
        //links= [SELECT Links__c FROM Category_Tab_Link__kav WHERE PublishStatus = 'online' AND Language = 'en_US' AND UrlName =: AdjustmentsTab.Category_Links__c].Links__c;            
     }         
         
        public String getAdjcatlinks() {
        return links;      
    }
    */
}