public class AuthorizationTabController{   
    /*
    public CatTabDefault__c AuthorizationTab {get; set;}     
    public list<CatTabDefault__c> catset {get; set;}
    public String links;   
     
     //Constructor with no arguments 
    public AuthorizationTabController() {
        
        catset = CatTabDefault__c.getAll().values();            
        AuthorizationTab = CatTabDefault__c.getInstance('Authorization');
        
        //SOQL to retrieve data from
        
        //links= [SELECT Links__c FROM Category_Tab_Link__kav WHERE PublishStatus = 'online' AND Language = 'en_US' AND UrlName =: AuthorizationTab.Category_Links__c].Links__c;
              
         }         
      
                
    public String getAuthorizationcatlinks() {
        return links;      
    }
	*/
}