public class PhoneBookTabController{
	/*
    public CatTabDefault__c Phone_BookTab {get; set;}  
    public list<CatTabDefault__c> catset {get; set;}    
    public String links;
     //Constructor with no arguments 
    public PhoneBookTabController() {
        
        catset = CatTabDefault__c.getAll().values();
        Phone_BookTab = CatTabDefault__c.getInstance('Phone Book');
        //SOQL to search articles filtered by Data-Categories
        //SOQL to retrieve data from
        
        //links= [SELECT Links__c FROM Category_Tab_Link__kav WHERE PublishStatus = 'online' AND Language = 'en_US' AND UrlName =: Phone_BookTab.Category_Links__c].Links__c;      
         }         
   
        public String getPhocatlinks() {
        return links;      
    }
    */
}