public class StopTriggerRecursion{
    
    public static boolean stopnwRelationshipsTrg = false;
    public static boolean stopVSPnwRelTrigger = false;
    public static boolean stopValidateCHOICNetwork = false;
    public static boolean stopcheckVSPnetworkProviderMethod = false;
    public static boolean stopApplyProgramID = false;
    public static boolean stopValidateMedicaidLicMeth = false;
    public static boolean stopNetRelsDeactivate = false;
    public static boolean stopconRoleNetRelAfterTriggerMethod = false;
    public static boolean stopAccountTrg = false;
    public static boolean stopDSAccountTrg = false;
    public static boolean stopContactTrg = false;  
    public static boolean stopUpdateVCCurrCust = false;
    public static boolean stopPracAcct = false;
    public static boolean stopContactVisionCareEndDate = false;
    public static boolean stopvalidateContact = false;
    public static boolean stopvalidateDocID = false;
    public static boolean stopcontactAfterTriggerMethod = false;
    
    public static boolean stopCRContactRoleTrigger_Handler = false;
    public static boolean stoppopulateFeeCodeONNR = false;
    public static boolean stopCRoleTrigger_Handler = false;
    
}