public class SubmitTabController{
   /*
    public CatTabDefault__c SubmitTab {get; set;}    
    public list<CatTabDefault__c> catset {get; set;}
           
    public String links;
    
     //Constructor with no arguments 
    public SubmitTabController() {
        
        catset = CatTabDefault__c.getAll().values();       
        SubmitTab = CatTabDefault__c.getInstance('Submit');
        //SOQL to retrieve data from
        
        //links= [SELECT Links__c FROM Category_Tab_Link__kav WHERE PublishStatus = 'online' AND Language = 'en_US' AND UrlName =: SubmitTab.Category_Links__c].Links__c;
              
         }         
      
       
     public String getSubcatlinks() {
        return links;      
    }
    */
}